#' @return 
#' \item{category}{numeric}
#' \item{code}{numeric}
#' \item{columns}{numeric}
#' \item{created}{character}
#' \item{credits}{numeric}
#' \item{dataset}{character}
#' \item{dataset_status}{logical}
#' \item{description}{character}
#' \item{input_fields}{character}
#' \item{locale}{character}
#' \item{max_columns}{numeric}
#' \item{max_rows}{numeric}
#' \item{model}{list}
#' \item{name}{character}
#' \item{number_of_predictions}{numeric}
#' \item{objective_fields}{character}
#' \item{private}{logical}
#' \item{range}{numeric}
#' \item{resource}{character}
#' \item{rows}{numeric}
#' \item{size}{numeric}
#' \item{source}{character}
#' \item{source_status}{logical}
#' \item{status}{list}
#' \item{tags}{AsIs}
#' \item{updated}{character}
